### ISSUE TITLE
弹窗组件循环依赖的问题

### ISSUE THREAD

**Issue by luoshilu** [1inus/angular2-layer#7]
你好，现在有弹窗1和弹窗2，在弹窗1上打开弹窗2，现在需要关闭弹窗2后打开弹窗1。

弹窗1组件中:

        this.l.dialog({

            title           : 弹窗2“”,

            dialogComponent : editAddrComponent,//editAddrComponent为弹窗2的组件

            parent          : this,

            closeAble       : true,

            data            : addr
        })

弹窗2组件中:

 setOnClose回调打开弹窗一

       this.l.dialog({

            title           :"弹窗1",

            align           :"top",

            dialogComponent : addrListComponent,//addrListComponent为弹窗1的组件

            closeAble       : true

        });

这样就导致两弹窗之间需要相互Import，angular会提醒Warnings while compiling。这怎么解决呢？望解答,谢谢。

**Comment by 1inus** [comment]
将弹窗的 ‘打开’ 和 ‘关闭’操作交给第三个操作者（在onclose回调里做），不要在这两个组件里面做
